name: Docker Build and Push

on:
  workflow_dispatch:

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker Image Name
        run: echo "IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/calculator-app" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t $IMAGE:latest .
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG_NAME=${GITHUB_REF#refs/tags/}
            echo "TAG=$TAG_NAME" >> $GITHUB_ENV
            docker tag $IMAGE:latest $IMAGE:$TAG_NAME
          fi

      - name: Push Docker images
        run: |
          docker push $IMAGE:latest
          if [[ -n "${TAG}" ]]; then
            docker push $IMAGE:$TAG
          fi

      - name: Install Docker Scout
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh
          docker scout version

      - name: Scan image for CVEs (Docker Scout CLI)
        run: docker scout cves $IMAGE:latest
